# -*- coding: utf-8 -*-
"""Practical-1_ML

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dDN-Hr8YFFnbG5En-QHhrLjfJN-mtuhX

Importing Numpy and Scipy
"""

import numpy as np
from scipy import constants
import pandas as pd

"""List"""

list=["Hello",15,1562.452,'a'] #Creating a List 
list[0]
print(list)

"""Dictionary"""

dictionary={1:"A",2:"B",3:"C"} # Creating a Dictionary
print(dictionary[1])
print(dictionary)

"""DataFrame"""

list=["Hello",15,1562.452,'a']

df=pd.DataFrame(list)
print(df)

"""Numpy Use"""

data=np.array([1,2,3,4,5])
for a in data:
  print(a)

"""Scipy Use"""

pi=constants.pi
radius=10
area=pi*radius*radius
print(" Area of Circle is : ",area)